name: Build

on:
  push:

jobs:
  get-shas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List Files
        run: ls /home/runner/work/plugin/plugin/
        
      - name: Controller SHA
        run: sha256sum /home/runner/work/plugin/plugin/app/Http/Controllers/Admin/MultiEggController.php

      - name: Index SHA
        run: sha256sum /home/runner/work/plugin/plugin/resources/views/admin/multiegg/index.blade.php

      - name: Support SHA
        run: sha256sum /home/runner/work/plugin/plugin/resources/views/admin/multiegg/support.blade.php

      - name: Nav SHA
        run: sha256sum /home/runner/work/plugin/plugin/resources/views/partials/admin/multiegg/nav.blade.php

      - name: Notice SHA
        run: sha256sum /home/runner/work/plugin/plugin/resources/views/partials/admin/multiegg/notice.blade.php
  make_tarball:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Make Tarball
        run: |
          cd /home/runner/work/plugin/plugin
          tar -zcvf addon.tar.gz app/ database/ resources/
      
      - name: Publish Tarball
        uses: actions/upload-artifact@v3
        with:
          name: addon.tar.gz
          path: /home/runner/work/plugin/plugin/addon.tar.gz

